/* Amplify Params - DO NOT EDIT
	API_RMS_BATCHTABLE_ARN
	API_RMS_BATCHTABLE_NAME
	API_RMS_GRAPHQLAPIENDPOINTOUTPUT
	API_RMS_GRAPHQLAPIIDOUTPUT
	API_RMS_HISTORYTABLE_ARN
	API_RMS_HISTORYTABLE_NAME
	API_RMS_ITEMSTABLE_ARN
	API_RMS_ITEMSTABLE_NAME
	API_RMS_MAINTABLE_ARN
	API_RMS_MAINTABLE_NAME
	API_RMS_SCHEDULETABLE_ARN
	API_RMS_SCHEDULETABLE_NAME
	API_RMS_TAGSTABLE_ARN
	API_RMS_TAGSTABLE_NAME
	ENV
	REGION
	STORAGE_BATCH_ARN
	STORAGE_BATCH_NAME
	STORAGE_BATCH_STREAMARN
	STORAGE_HISTORY_ARN
	STORAGE_HISTORY_NAME
	STORAGE_HISTORY_STREAMARN
	STORAGE_ITEMS_ARN
	STORAGE_ITEMS_NAME
	STORAGE_ITEMS_STREAMARN
	STORAGE_MAIN_ARN
	STORAGE_MAIN_NAME
	STORAGE_MAIN_STREAMARN
	STORAGE_RMS_BUCKETNAME
	STORAGE_SCHEDULE_ARN
	STORAGE_SCHEDULE_NAME
	STORAGE_SCHEDULE_STREAMARN
	STORAGE_TAGS_ARN
	STORAGE_TAGS_NAME
	STORAGE_TAGS_STREAMARN
	STORAGE_TRANSACTIONS_ARN
	STORAGE_TRANSACTIONS_NAME
	STORAGE_TRANSACTIONS_STREAMARN
Amplify Params - DO NOT EDIT */

/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
    console.log(`EVENT: ${JSON.stringify(event)}`);
    return {
        statusCode: 200,
    //  Uncomment below to enable CORS requests
    //  headers: {
    //      "Access-Control-Allow-Origin": "*",
    //      "Access-Control-Allow-Headers": "*"
    //  },
        body: JSON.stringify('Hello from Lambda!'),
    };
};
