# Workflow to run backend tests on push
name: Backend CI

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install, build and unit test
        run: |
          npm install
          npm run build
          npm run test:unit

      - name: code coverage
        uses: artiomtr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
          skip-step: all